/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputParamaterChooserPanel.java
 *
 * Created on May 17, 2011, 3:20:59 PM
 */

package jgaf.procedure;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author hanis
 */
public class InputParamaterForcedOptionsPanel extends javax.swing.JPanel implements ParameterPanInterface{

    private ProcedureParameter parameter;
    private List<String> forcedOptions;
    
    public InputParamaterForcedOptionsPanel(ProcedureParameter parameter) {
        this.parameter = parameter;
         parameter.getForcedOptions();
        initComponents();
        initMyComponents();
        centerDialog();
    }



    private void initMyComponents() {
        parameterLabel.setText(parameter.getDescription());
        Vector<String> forcedOptionsV= new Vector<String>(parameter.getForcedOptions());
        parameterBox.setModel(new DefaultComboBoxModel(forcedOptionsV));
    }

    public void setParameter() {
        parameter.setText((String) parameterBox.getSelectedItem());
    }


    private void centerDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parameterLabel = new javax.swing.JLabel();
        parameterBox = new javax.swing.JComboBox();

        parameterLabel.setText("jLabel1");

        parameterBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        parameterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parameterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parameterBox, 0, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parameterLabel)
                    .addComponent(parameterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void parameterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox parameterBox;
    private javax.swing.JLabel parameterLabel;
    // End of variables declaration//GEN-END:variables

}
